stages:
  - build
  - test

build:
  image: ubuntu:20.04
  stage: build
  before_script:
    - apt -y update
    - apt -y install apt-utils
    - apt -y install net-tools python3.8 python3-pip mysql-client libmysqlclient-dev
    - apt -y upgrade
    - pip3 install -r ../requirements.txt
  script:
    - python manage.py makemigrations
    - python manage.py migrate
    - python manage.py check
  only:
    refs:
      - merge_requests


test:
  image: ubuntu:20.04
  stage: test
  before_script:
    - apt -y update
    - apt -y install apt-utils
    - apt -y install net-tools python3.8 python3-pip mysql-client libmysqlclient-dev
    - apt -y upgrade
    - pip3 install -r ../requirements.txt
  script:
    - python manage.py test
  only:
    refs:
      - merge_requests
